version: "3.9"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Some_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
